apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-tek
  namespace: tekpipe
imagePullSecrets:
  - name: regcreds
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-tek
rules:
- apiGroups: ["", "apps"]
  resources:
  - pods
  - services
  - configmaps
  - deployments
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-tek1
  namespace: roar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-tek
subjects:
- kind: ServiceAccount
  name: sa-tek
  namespace: tekpipe
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-tek2
  namespace: tekpipe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-tek
subjects:
- kind: ServiceAccount
  name: sa-tek
  namespace: tekpipe
