apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone- 
  labels: 
    tekton.dev/task: git-clone
spec:
  taskRef:
    name: git-clone
  params: 
    - name: url
      value: https://github.com/skillrepos/tekton-docker-k8s.git
    - name: revision
      value: main
  workspaces: 
    - name: output
      persistentVolumeClaim:
        claimName: git-files-pvc
