apiVersion: v1
kind: ServiceAccount
metadata:
  name: rt-sa
  namespace: tekpipe
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rt-role
rules:
# EventListeners need to be able to fetch all namespaced resources
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
# configmaps is needed for updating logging config
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["tekton-triggers"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rt-rb
subjects:
- kind: ServiceAccount
  name: rt-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rt-role
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rt-cr
rules:
  # EventListeners need to be able to fetch any clustertriggerbindings
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings", "clusterinterceptors"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rt-crb
subjects:
- kind: ServiceAccount
  name: rt-sa
  namespace: tekpipe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rt-cr
