kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: taskrun-debug-
spec:
  debug:
    breakpoint: ["onFailure"]
  taskSpec:
    results:
      - name: exitMsg
        description: The exit message for the step
    steps:
      - name: step1-force-fail   
        image: alpine
        script: |
          echo Aborting... | tee $(results.exitMsg.path)
          date >> $(results.exitMsg.path)
          exit 1
      - name: step2-final
        image: alpine
        script: |
          echo "Step 2 Done!"


         
